apiVersion: v1
kind: Service
metadata:
  name: telemetry-service-service
spec:
  selector:
    app: telemetry-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer