apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-service
  template:
    metadata:
      labels:
        app: telemetry-service
    spec:
      containers:
        - name: telemetry-service
          image: telemetry-service
          ports:
            - containerPort: 8080