apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-app
  template:
    metadata:
      labels:
        app: telemetry-app
    spec:
      containers:
        - name: telemetry-app
          image: telemetry-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080